services:
  - type: web
    name: file-converter-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 22.16.0
      - key: PORT
        value: 5001
      - key: FRONTEND_URL
        value: https://your-frontend-domain-on-render.com
      - key: CONVERSION_TIMEOUT
        value: 120000
    preDeployCommand: |
      apt-get update && apt-get install -y ffmpeg libvips-dev poppler-utils